// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerDiary.Persistence;

#nullable disable

namespace PowerDiary.Persistence.Migrations
{
    [DbContext(typeof(PowerDiaryDbContext))]
    partial class PowerDiaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PowerDiary.Domain.ChatEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatEvents", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PowerDiary.Domain.UserComment", b =>
                {
                    b.HasBaseType("PowerDiary.Domain.ChatEvent");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = 19,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 10, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "Hello"
                        },
                        new
                        {
                            Id = 20,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 12, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 21,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 22,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "Hey people"
                        },
                        new
                        {
                            Id = 23,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 19, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "Hello again"
                        },
                        new
                        {
                            Id = 24,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 12, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "Hey Alice"
                        },
                        new
                        {
                            Id = 25,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "John",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 26,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "Hello all"
                        },
                        new
                        {
                            Id = 27,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Maria",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 28,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 29,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Maria",
                            Message = "Hi George"
                        },
                        new
                        {
                            Id = 30,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 27, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "Hello Maria"
                        },
                        new
                        {
                            Id = 31,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "Hello"
                        },
                        new
                        {
                            Id = 32,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Maria",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 33,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 34,
                            OccurredAt = new DateTime(2024, 2, 3, 20, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 35,
                            OccurredAt = new DateTime(2024, 2, 3, 20, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "John",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 36,
                            OccurredAt = new DateTime(2024, 2, 3, 20, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "Hello all"
                        },
                        new
                        {
                            Id = 37,
                            OccurredAt = new DateTime(2024, 2, 3, 21, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Maria",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 38,
                            OccurredAt = new DateTime(2024, 2, 3, 21, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "George",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 39,
                            OccurredAt = new DateTime(2024, 2, 4, 19, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "Hello"
                        },
                        new
                        {
                            Id = 40,
                            OccurredAt = new DateTime(2024, 2, 4, 19, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Maria",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 41,
                            OccurredAt = new DateTime(2024, 2, 4, 19, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Bob",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 42,
                            OccurredAt = new DateTime(2024, 2, 4, 20, 5, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "How are you?"
                        },
                        new
                        {
                            Id = 43,
                            OccurredAt = new DateTime(2024, 2, 4, 20, 10, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "John",
                            Message = "Hi"
                        },
                        new
                        {
                            Id = 44,
                            OccurredAt = new DateTime(2024, 2, 4, 20, 10, 16, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            UserName = "Alice",
                            Message = "Hello all"
                        });
                });

            modelBuilder.Entity("PowerDiary.Domain.UserEntered", b =>
                {
                    b.HasBaseType("PowerDiary.Domain.ChatEvent");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 5, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 7, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 3,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "George"
                        },
                        new
                        {
                            Id = 4,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 5, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 5,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 7, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "John"
                        },
                        new
                        {
                            Id = 6,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Maria"
                        },
                        new
                        {
                            Id = 7,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 10, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 8,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Maria"
                        },
                        new
                        {
                            Id = 9,
                            OccurredAt = new DateTime(2024, 2, 3, 20, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 10,
                            OccurredAt = new DateTime(2024, 2, 3, 20, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserName = "John"
                        });
                });

            modelBuilder.Entity("PowerDiary.Domain.UserHighFive", b =>
                {
                    b.HasBaseType("PowerDiary.Domain.ChatEvent");

                    b.Property<string>("ToUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = 45,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 13, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Bob",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 46,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "John",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 47,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Alice",
                            ToUserName = "Bob"
                        },
                        new
                        {
                            Id = 48,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 19, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "George",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 49,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 13, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Bob",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 50,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "John",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 51,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Alice",
                            ToUserName = "Bob"
                        },
                        new
                        {
                            Id = 52,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 19, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "George",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 53,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 13, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Bob",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 54,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "John",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 55,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Alice",
                            ToUserName = "Bob"
                        },
                        new
                        {
                            Id = 56,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 19, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "George",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 57,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 13, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Bob",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 58,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "John",
                            ToUserName = "Alice"
                        },
                        new
                        {
                            Id = 59,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 17, 16, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            UserName = "Alice",
                            ToUserName = "Bob"
                        });
                });

            modelBuilder.Entity("PowerDiary.Domain.UserLeft", b =>
                {
                    b.HasBaseType("PowerDiary.Domain.ChatEvent");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 11,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 15, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 12,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 27, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 13,
                            OccurredAt = new DateTime(2024, 2, 2, 18, 30, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "John"
                        },
                        new
                        {
                            Id = 14,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 10, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 15,
                            OccurredAt = new DateTime(2024, 2, 2, 20, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "John"
                        },
                        new
                        {
                            Id = 16,
                            OccurredAt = new DateTime(2024, 2, 2, 21, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Maria"
                        },
                        new
                        {
                            Id = 17,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 20, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 18,
                            OccurredAt = new DateTime(2024, 2, 3, 19, 25, 16, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            UserName = "Maria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
